kakao oAuth 추가
work-at/backend pull request #13
Opened 2022-06-17 14:28 UTC by seung-00

#### AS-IS

#### TO-BE
인가 코드, access token 내려 받는 동선까지 작업

#### 리뷰시 중점 사항

#### 참조사항
[wiki](https://oil-force-e60.notion.site/oAuth-0daa00c39d7d4f4d83c894521300d920)

resolves #12

2022-06-17 15:34 UTC, sypark9646 approved these changes

2022-06-17 15:34 UTC, sypark9646 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +			RestTemplate restTemplate = new RestTemplate();
RestTemplate 은 thread-safe 하기 때문에 아래처럼 빈으로 만들어두고 
정해진 갯수만 생성해서 injection 하면 자원을 아낄 수 있을 것 같아요~!

보통은 connection pool 을 만드는데, 이건 다음 pr에 제가 포함시키겠습니다!

```java
@Configuration
public class RestTemplateConfig {
...
	@Bean
	RestTemplate restTemplate(...) {
		return new RestTemplate(...);
	}
}
```

2022-06-17 15:34 UTC, sypark9646 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +			final ResponseEntity<KakaoOAuthTokenResponse> exchange = restTemplate.exchange(AUTH_URL,
`exchange` 를 final 로 두신 이유를 알 수 있을까요?!

2022-06-17 15:34 UTC, sypark9646 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +		} catch (Exception e) {
```
By default, the RestTemplate will throw one of these exceptions in the case of an HTTP error:
HttpClientErrorException – in the case of HTTP status 4xx
HttpServerErrorException – in the case of HTTP status 5xx
UnknownHttpStatusCodeException – in the case of an unknown HTTP status
```

위에 있는 Exception 들은 BusinessException 을 상속하고 있는 새로운 Exception으로 정의해 두지 않았기 때문에, 
이렇게 throw e 로 던지면 아마 `ControllerAdvice` 가 잡지 못할 것 같아요!! 
(왜냐하면 controlleradvice에 businessException만 등록해놨기 때문에)
```java
@ControllerAdvice
public class GlobalExceptionHandler {

	@ExceptionHandler(BusinessException.class)
	protected ResponseEntity<ErrorResponse> handleBusinessException(BusinessException e) {
		return new ResponseEntity<>(ErrorResponse.of(e.getCode().value(), e.getMessage()), e.getCode());
	}
}
```

따라서 exception 폴더에 정의해둔 것중에 골라서 throw 하거나, 
승영님이 알맞게 BusinessException 을 상속하여 만든 Exception 을 throw 하셔야 할 것 같습니다

2022-06-17 15:34 UTC, sypark9646 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +	private static final String CLIENT_ID = "7052acd04b3385c80fac9bb40d8b5a32";
요건 api access 토큰인가요?? yml 파일에 적어두고 `@Value` 로 읽으면 좋지 않을까요?!
나중에 prod 할 때는 도커 시크릿 변수로 둘 수도 있을 것 같구요

2022-06-17 15:34 UTC, sypark9646 commented on src/main/java/com/workat/controller/AuthorizationController.java
> +	@Autowired
필드 주입은 유닛 테스트가 어려워서 지양한다고 하더라구요..!!
저는 주입할 필드를 final로 두고 `@RequiredArgsConstructor` 요걸 주로 사용하게 되는데 @dev-donghwan 님은 어떠세요?

2022-06-18 07:14 UTC, seung-00 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +			final ResponseEntity<KakaoOAuthTokenResponse> exchange = restTemplate.exchange(AUTH_URL,
예제 코드를 찾다가 final 로 두는 경우가 많아서 써봤는데요. 저는 respones 값이 변경될 일이 없으니까 readonly 로 할당한다고 이해하고 썼어요.
그런데 다시 보니까 굳이 지역 변수 두지 말고 아래처럼 바로 리턴할 걸 그랬나 싶네요

```java
...
return restTemplate
    .exchange(AUTH_URL, HttpMethod.POST, request, KakaoOAuthTokenResponse.class)
    .getBody();
```

2022-06-18 07:19 UTC, seung-00 commented on src/main/java/com/workat/controller/AuthorizationController.java
> +	@Autowired
오 저도 @RequiredArgsConstructor 로 생성자 주입하는게 더 좋습니다.

사실 쏘쏘님의 mail-authorization 컨트롤러 참고했던 것인데, @RequiredArgsConstructor 로 다시 수정하겠습니다

2022-06-18 07:21 UTC, seung-00 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +	private static final String CLIENT_ID = "7052acd04b3385c80fac9bb40d8b5a32";
오 그렇군요 그렇게 수정해보겠습니다~

2022-06-18 08:19 UTC, dev-donghwan requested changes

2022-06-18 08:19 UTC, dev-donghwan commented on src/main/java/com/workat/controller/AuthorizationController.java
> +	@Autowired
@sypark9646 @seung-00 
저도 특수하게 생성자에서 핸들링 해야할게 있지않으면 @RequiredArgsConstructor 사용합니다.
특수한 경우라면 yaml에서 @Value로 뭘 받았는데 바로사용하는게 아니라 가공을 한다던가? 이런느낌

2022-06-18 08:19 UTC, dev-donghwan commented on src/main/java/com/workat/controller/AuthorizationController.java
> +@RequestMapping("/api/v1/auth")
@seung-00 
그리고 저는 이거 선호하지 않는게 예를들어 v2가 있을 경우엔 모든 api 다 수정해야해서 api까지만 넣던가 아예 넣지않는편입니다.

2022-06-18 08:19 UTC, dev-donghwan commented on src/main/java/com/workat/dto/KakaoOAuthAccessToken.java
> +}
@seung-00 
Dto는 끝에 Dto를 붙여주는게 좋다고 생각합니다.
그리고 DTO는 @RequiredArgsConstructor보단 
@NoArgsConstructor(access = PROTECTED) + 생성패턴 조합이 좋은거같습니다. 이유는 저렇게 만들면 진짜 불변이라고 보기 어려운데 new로 생성이 가능하기때문에 진정한 불변이라고 보기 조금 어려운면이 있는거 같습니다.

2022-06-18 08:19 UTC, dev-donghwan commented on src/main/java/com/workat/dto/KakaoOAuthTokenResponse.java
> +@NoArgsConstructor
@seung-00 
오 여기서 NoArgsConstructor에 access 권한제어만 해주면 좋을거같습니다

2022-06-18 11:43 UTC, sypark9646 commented on src/main/java/com/workat/controller/AuthorizationController.java
> +	@Autowired
ㅋㅋㅋㅋㅋㅋㅋ넹 저기선 그냥 돌아가는지만 테스트한거라~~ 저도 `@RequiredArgsConstructor` 가 좋습니다!!

2022-06-18 11:48 UTC, sypark9646 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +			final ResponseEntity<KakaoOAuthTokenResponse> exchange = restTemplate.exchange(AUTH_URL,
아하 근데 객체는 final 로 두더라도 내부 값들은 변경이 가능했던걸로 알고 있어서(주소값은 변경 불가) final 로 두신 이유가 궁금했어요~! 저도 바로 리턴하는게 깔끔해보이긴 하네요

2022-06-18 11:53 UTC, sypark9646 commented on src/main/java/com/workat/dto/KakaoOAuthAccessToken.java
> +}
저도 dto 붙여주는걸 선호하긴 하지만 dto 패키지 안에 있으니 생략하시는 분들도 계시더라구용
근데 Request인지 Response인지 구분해주는건 중요하다고 생각합니다~!

2022-06-19 06:12 UTC, seung-00 commented
@sypark9646  @dev-donghwan 
리뷰 반영했습니다~ 꼼꼼하게 봐주셔서 감사합니다 👍

2022-06-19 06:15 UTC, seung-00 commented on src/main/java/com/workat/dto/KakaoOAuthAccessToken.java
> +}
넵 아래 커밋에 반영해봤습니다~ ㅎㅎㅎ 

* 생성자 수정: 018ac20
* 네이밍 변경: 39e5e67

2022-06-19 06:16 UTC, seung-00 commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +		} catch (Exception e) {
감사합니다 제가 잘 모르고 사용했었네요 ㅎㅎㅎ
아래 커밋에 수정해봤는데, 어떤 것 같으세요? 카카오 api 에러 메세지가 json 포맷도 아니고, 그대로 클라이언트에게 노출시키는 것도 별로 같아서 code 만 받아서 내리게 해봤어요

* 33c36f1

2022-06-19 06:21 UTC, sypark9646 approved these changes

2022-06-19 08:45 UTC, dev-donghwan requested changes

2022-06-19 08:45 UTC, dev-donghwan commented on src/main/java/com/workat/controller/AuthorizationController.java
> +@RequestMapping("/api/auth")
@seung-00 
앗 승영님 제가 설명을 제대로 못드린거 같습니다.
/api/v1/auth/xxx은 맞는데 저걸 전부 RequestMapping에 박지는 않는다는 의미였습니다!
그래서 만약 박는다면 @RequestMaaping("/api")까지만 한다는 의미였습니다

2022-06-19 08:45 UTC, dev-donghwan commented on src/main/java/com/workat/controller/AuthorizationController.java
> +	public ResponseEntity<KakaoOAuthAccessTokenDto> issueToken(@RequestBody KakaoOAuthTokenRequestDto request) {
@seung-00 
아 그리고 그때 말씀드린게
Request와 Response는 굳이 dto를 안붙여도 된다는 의미였습니다.
xxxRequest
xxxResponse
xxxDto

2022-06-19 08:45 UTC, dev-donghwan commented on src/main/java/com/workat/dto/KakaoOAuthAccessTokenDto.java
> +	public static KakaoOAuthAccessTokenDto from(String accessToken) {
@seung-00 
https://7942yongdae.tistory.com/147
보통 이런경우는 of로 하는걸로 알고 있습니다.
from은 보통 entity -> dto 또는 dto -> dto인 경우?에 사용했던거 같아요. 
근데 사실 이름은 상관없긴하지만 제 경험상 파라미터로 변수를 받아서 처리하면 보통 of로 처리했던거 같습니다!

2022-06-19 08:45 UTC, dev-donghwan commented on src/main/java/com/workat/dto/KakaoOAuthTokenResponseDto.java
> +	}
@seung-00 
이거 근데 아마 그냥 @Builder를 11번째 라인같은곳에 추가해도 바로 적용이 되는걸로 알고있습니다. 혹시 몰라서 알고 계시라고 적어둡니다!

2022-06-19 08:45 UTC, dev-donghwan commented on src/main/java/com/workat/service/KakaoOAuthService.java
> +	private String CLIENT_ID;
@seung-00 
혹시 하시는김에 개행을 한번!!

2022-06-19 08:49 UTC, seung-00 commented on src/main/java/com/workat/controller/AuthorizationController.java
> +@RequestMapping("/api/auth")
아하~ 그렇겠네요. 수정하겠습니다 ㅎㅎ

2022-06-19 08:50 UTC, seung-00 commented on src/main/java/com/workat/dto/KakaoOAuthTokenResponseDto.java
> +	}
클래스 위에 말씀하시는거죠? 요거 NoArgsConstructor 와 같이 쓰면 이슈가 있더라고요 ㅠ 아래 링크 참고하시면 이유가 나옵니다
https://wooktae.tistory.com/34

2022-06-19 08:50 UTC, seung-00 commented on src/main/java/com/workat/dto/KakaoOAuthAccessTokenDto.java
> +	public static KakaoOAuthAccessTokenDto from(String accessToken) {
오 그 편이 더 좋을 것 같네요~

2022-06-19 15:01 UTC, dev-donghwan commented on src/main/java/com/workat/dto/KakaoOAuthTokenResponseDto.java
> +	}
@seung-00 
오... 이건 몰랐네요

2022-06-19 15:15 UTC, seung-00 commented
@dev-donghwan 
리뷰 넘넘 감사합니다~ ㅎㅎㅎ 반영했어요

2022-06-19 15:56 UTC, dev-donghwan approved these changes

2022-06-19 15:57 UTC, merged