회원 구현
work-at/backend pull request #24
Opened 2022-07-01 13:59 UTC by seung-00

#### AS-IS
* 카카오 로그인을 통해 access token 을 클라이언트가 내려받는 과정까지만 구현되어 있던 상태

#### TO-BE
* access token 검증 로직 추가
  * POST https://kapi.kakao.com/v1/user/access_token_info API 로 검증함
  * `kakaoOauthService.getId()`, `OauthTokenValidationAspect.validate()`
  * AOP 구현 (@OauthTokenValidation)

* 회원 가입 추가
  * 기존 우리가 얘기했던 엔티티에서 조금 변경됨
    * id: auto increament number -> uuid (회원은 모든 환경에서 유일해야 하므로)
    * oAuth id: string -> long
    * [notion](https://oil-force-e60.notion.site/17c02802cb4049dea7d6b376cc087e70) 에 반영함

* OAuth ... -> Oauth... 으로 네이밍 변경
  * Data JPA 에서 findBy... 을 할 때 OAuth 를 카멜 케이스로 제대로 인식 못하는 이슈가 있었음. 그래서 그냥 Oauth 로 다 통일시킴

#### 리뷰시 중점 사항

#### 참조사항

resolve #22

2022-07-01 15:36 UTC, dev-donghwan requested changes

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/api/auth/service/KakaoOauthService.java
> +	private String CLIENT_ID;
제 개인적인 의견인데 순서는 상수일 수록, 단순한 변수 (primitive 또는 wrapper 클래스)일 수록, Object 타입 클래스일 수록을 우선순위로 두고 있는데, 쉽게 CLIEND_ID랑 restTemplate랑 위치가 바뀌는게 어떨까 싶고 CLINED_ID는 컨벤션이 위배되는거 같아요 굳이 상수랑 네이밍 동일하게 갈 필요없을거 같습니다.

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/api/user/controller/UserController.java
> +	public ResponseEntity signUp(@RequestHeader("Authorization") String accessToken, @RequestBody SignUpDto signUpDto) {
SignUpDto > SignUpRequest가 좋을거 같습니다.

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/api/user/repository/UserRepository.java
> +@Repository
이거 근데 JpaRepository 붙어있으면 안붙여도 되긴합니다.

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/api/user/service/UserService.java
> +@RequiredArgsConstructor
그리고 이거도 제 개인적인 버릇이긴한데 저는 이 클래스의 정체성?이 가장 아래로 가야된다고 생각하거든요
저는 이런경우
@Slf4j
@RequiredArgs...
@Service
이런식으로 작성합니다. 사실 안해도 무방하긴해요

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/api/user/service/UserService.java
> +			log.error(String.valueOf(user.getId()));
요고도 로그를 조금 더 자세하게 남기면 어떨까요?
예를들어 signUp already exist error : user.getId()

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/api/user/service/UserService.java
> +	public void signUp(KakaoOauthIdDto idDto, SignUpDto signUpDto) {
음 이런경우 굳이 Dto로 안받아도 될거같아요. 아마 제가 그때 레이어간 데이터 전송에 Dto라고 해서 그럴 수 헷갈리셨을 수 있는데 저는 이런경우 parameter로 id만 넘겨도 충분하다고 생각합니다

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/common/annotation/aspect/OauthTokenValidationAspect.java
> +			log.info(String.format("[OAuth 2.0] Authentication Success : %s", res.getBody().getId()));
정확히 이해하지 못했는데 혹시 설명 한번 가능하실까요?

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/domain/auth/OauthType.java
> +public enum OauthType {
이넘 분리 아주 좋은거같습니다 확장성까지 고려한 설계

2022-07-01 15:36 UTC, dev-donghwan commented on src/main/java/com/workat/domain/user/User.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
저는 이거도 위에서 말씀드린거처럼 작성하는게 좋지않을까? 생각합니다.

2022-07-01 19:28 UTC, sypark9646 commented on src/main/java/com/workat/domain/user/User.java
> +	@Column
요건 유저 구분을 위한것이니 `unique` 인덱스를 걸어주어야 할 것 같습니다!!

2022-07-01 19:47 UTC, sypark9646 approved these changes
고생하셨습니다~!

2022-07-01 19:47 UTC, sypark9646 commented on src/main/java/com/workat/domain/user/User.java
> +	private long oauthId;
요건 유저 구분을 위한것이니 unique 인덱스를 걸어주어야 할 것 같습니다

2022-07-01 19:47 UTC, sypark9646 commented on src/main/java/com/workat/domain/user/User.java
> +	@Column
여기서 저장한 유저 위치 정보는 언제 사용하는걸까요? 궁금해서 여쭤봅니다!!

2022-07-01 19:47 UTC, sypark9646 commented on src/main/java/com/workat/domain/auth/OauthType.java
> +public enum OauthType {
굿굿~~

2022-07-01 19:47 UTC, sypark9646 commented on src/main/java/com/workat/common/annotation/aspect/OauthTokenValidationAspect.java
> +			throw new UnAuthorizedException("oauth error");
아 여기서 `UnAuthorizedException` 을 리턴하고 싶으셨군요
제가 RestTemplate Exception Handler에 아예 HttpStatusCodeException 이걸 등록해놔서 여기서 안잡히는것 같은데
예외적으로 여기서 처리를 할 수 있는지 저도 알아볼게요

2022-07-01 19:47 UTC, sypark9646 commented on src/main/java/com/workat/common/annotation/aspect/OauthTokenValidationAspect.java
> +			log.info(String.format("[OAuth 2.0] Authentication Success : %s", res.getBody().getId()));
저두용...!!

`@OauthTokenValidation` 을 붙인 서버에 들어오는 모든 요청들을 확인하는걸까요?!
https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#get-token-info-request

만약 어노테이션을 붙인 서버에 들어오는 모든 요청들을 확인하는 로직을 구현하신 것이라면,
저희가 발급하는 JWT 토큰을 확인할 때와 `@OauthTokenValidation` 을 붙여서 validation을 하는 경우 
두 가지가 어떻게 구분해서 써야하는지 궁금합니다.

`@OauthTokenValidation`는 회원가입때와 토큰이 만료되어서 카카오 재로그인을 해야할 때 정도만 쓰는건가요,,?

2022-07-02 07:08 UTC, seung-00 commented on src/main/java/com/workat/common/annotation/aspect/OauthTokenValidationAspect.java
> +			log.info(String.format("[OAuth 2.0] Authentication Success : %s", res.getBody().getId()));
소연님이 올려주신 링크가 카카오 access token 검증을 하는 api 인데요. signUp 메서드에서처럼 @OauthTokenValidation 을 붙인 요청을 검증하는 용도로 개발했습니다. 
그런데, 생각해보니까 저희가 JWT 를 만들어서 내려주기로 정했던 걸 잊었네요... 그러면 로직이 조금 바뀔 것 같습니다.

2022-07-02 08:54 UTC, seung-00 commented on src/main/java/com/workat/api/user/repository/UserRepository.java
> +@Repository
넵 반영했습니다
c7cb75d8a72b347dcfbac68cf8c51a4683438fe2

2022-07-02 08:54 UTC, seung-00 commented on src/main/java/com/workat/api/user/service/UserService.java
> +@RequiredArgsConstructor
좋은 것 같아요 ㅎㅎ 반영했습니다~
61353db1b4b40a4dc7bbce1a37db349b46b8794c

2022-07-02 08:54 UTC, seung-00 commented on src/main/java/com/workat/api/user/service/UserService.java
> +	public void signUp(KakaoOauthIdDto idDto, SignUpDto signUpDto) {
아하 ㅎㅎㅎ 넵 수정했습니다~
623da9d3192d3ae89ef920402c248cb7bb5b52ce

2022-07-02 08:54 UTC, seung-00 commented on src/main/java/com/workat/api/user/service/UserService.java
> +			log.error(String.valueOf(user.getId()));
좋은 것 같습니다~ 반영했어요
409f7b955e8d021c9528d0b5b4393fa88a0dd705

2022-07-02 08:54 UTC, seung-00 commented on src/main/java/com/workat/domain/user/User.java
> +	private long oauthId;
그게 좋겠네요 ㅎㅎㅎ 반영했습니다~
e1ed61d15888615117ad4b367bdfe7313a6b25ef

2022-07-02 08:54 UTC, seung-00 commented on src/main/java/com/workat/domain/user/User.java
> +	@Column
지도에서 사용하는 것이라고 막연하게 생각했는데요. 불필요해 보이시나요?

2022-07-02 08:55 UTC, seung-00 commented on src/main/java/com/workat/api/user/controller/UserController.java
> +	public ResponseEntity signUp(@RequestHeader("Authorization") String accessToken, @RequestBody SignUpDto signUpDto) {
넵 반영했습니다
https://github.com/work-at/backend/commit/c7cb75d8a72b347dcfbac68cf8c51a4683438fe2

2022-07-02 11:32 UTC, dev-donghwan approved these changes
Good

2022-07-03 06:44 UTC, merged