Refactor/address save and worker size
work-at/backend pull request #51
Opened 2022-07-11 14:07 UTC by sypark9646

#### AS-IS

#### TO-BE
- save address 와 주변 워케이셔너 사이즈 조회 api 분리

#### 리뷰시 중점 사항

#### 참조사항

2022-07-11 15:29 UTC, seung-00 approved these changes
👍

2022-07-11 15:29 UTC, seung-00 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
null 일 때 안 보여주는 친구 같은데, 요기 붙인 이유가 있나요?

2022-07-11 16:33 UTC, dev-donghwan commented on src/main/java/com/workat/api/map/service/WorkerService.java
> +		if (metaOnly) {
메타 온리는 어디서 쓰는건가요?

2022-07-12 02:04 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
@seung-00 @dev-donghwan 
현재 주위 워케이셔너 `전체리스트`를 가져올 땐 `/api/v1/map/workers`을 사용 중이고
주위 워케이셔너 `count`만 가져올 땐 `/api/v1/map/workers?metaOnly=true` 로 가져오도록 했습니다

주위 워케이셔너 수를 가져올 경우 메타데이터(주위 워케이셔너 수)만 보내주면 될 것 같아서 리스트 부분은 안보이게 처리했습니다.
혹시 워케이셔너 전체리스트, 워케이셔너 수 조회 path 나 dto 분리를 하는게 좋을 것 같다고 하시면 그렇게 하겠습니다!

2022-07-12 02:04 UTC, sypark9646 commented on src/main/java/com/workat/api/map/service/WorkerService.java
> +		if (metaOnly) {
동일한 내용인 것 같아 위에 달았습니다.

2022-07-12 02:16 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
<img width="843" alt="image" src="https://user-images.githubusercontent.com/46469385/178394062-dc55a174-88a6-4da9-ba7a-717ece5aa3b5.png">
<img width="965" alt="image" src="https://user-images.githubusercontent.com/46469385/178394034-5461c703-9a35-4fab-842c-18dd7e7ec407.png">

2022-07-12 13:01 UTC, dev-donghwan commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
@sypark9646 저는 dto의 활용은 크게 상관없을거 같은데 api가 meatOnly=true보단 더 명확하게 /workers/counting이라든가 더 좋은 방법이 있지 않을까 싶네요! meatOnly true false로 나뉘는 상황보단 더 명시적인게 좋은거 같습니다.

2022-07-12 13:02 UTC, dev-donghwan requested changes
음 저는 위에 내용이 변경이 좀 필요하다고 느낍니다!

2022-07-12 13:18 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
저는 worker에 대한 counting이라서 둘이 별도의 리소스라고 생각들지 않아요
그래서 이걸 독립적으로 실행할 수 있게 만들어야 하나 싶다는 생각이 들어요

2022-07-12 13:26 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
@dev-donghwan 
제가 좀 헷갈려서 그러는데 `/api/v1/map/workers/counting` 이건 worker의 하위 리소스 조회를 나타낸다는 생각이 들어서요
worker에 대한 counting 을 조회하는데 별도의 리소스라고 생각이 들지 않아서 query string 으로 조회하도록 했는데,
이걸 path를 분리해서 독립적으로 실행할 수 있게 만들어야 할까요?

2022-07-12 13:39 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
좀 덧붙이자면, 마커 조회의 경우는 location 필드만 가져오기 때문에(하위 리소스 조회로도 볼 수 있을 것 같음)
`/api/v1/map/workers/location` 등으로 엔드 포인트 분리를 할 수 있겠다는 생각입니다

2022-07-15 09:16 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
@dev-donghwan 아니면 이런 방법은 어떻게 생각하시나요? 커스텀 헤더에 넣는 방법인데 괜찮아 보여서 가져와봤습니다~
[Getting a count of returns seen by a RESTful request](https://stackoverflow.com/questions/1610862/getting-a-count-of-returns-seen-by-a-restful-request)
그런데 옛날에 안드로이드 하시던 민호님이 헤더에 뭐 넣으면 귀찮다고 말씀해주셨던 기억이 나긴 한다..ㅋㅋㅋㅋㅋㅋ
`/api/v1/map/workers/counting` 이 방식이 프론트 입장에서는 더 편해서 추천을 하시는건가요? 
아니면 불리언 값은 query 파라미터로 사용하지 않는 추세라서 말씀해주신걸까요?

오픈 api들은 어떻게 구현하고 있는지 좀 찾아봤는데
불리언 타입 `include_entities`, `meta_query` 등으로 엔티티를 제외한 값만 가져오는 예시나
아니면 저렇게 커스텀 헤더에서 갯수를 가져오는 예시가 종종 보여서요

2022-07-15 17:31 UTC, dev-donghwan commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
@sypark9646 
음 댓글 다신걸 좀 늦게봤네요ㅠㅋㅋ 

사실 다른 의도보다는 제 개인적인 의견이라 일단 제가 말씀드린 의도는 위에 두 경우가 meatOnly true와 그게 아닌경우로 나누는게 어색하다? 또는 합리적인가?라는 생각이 들어서 말씀드린 케이스인거 같습니다.

제 생각엔 /workers는 full data인데, workers?meatOnly=true는 count인데 이 구조가 살짝 의도만 봤을때 판단이 안된다랄까요...

아래 말씀하신 헤더 방법도 안써봐서 잘은 모르겠지만 굉장히 간단한 구조인데 굳이 필요가 없어보입니다.... 그리고 workers/counting에서 저는 /가 항상 하위를 나타낸다고는 생각하지 않아서 약간 특수한 상황이니 대입이 가능할까...? 싶기도하네요. 근데 꼭 이거말고도 말씀하신 
 boolean보다는 명시적인 type을 주시는게 어떤가 생각이 드네요
workers?type=count, workers?type=dto라던가?... 아니면 프론트에 여쭤보는거도 좋을거같아요

2022-07-16 04:34 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
query string이나 헤더 방법 등 저는 굳이라고 생각되기보다는
count를 구하는 경우, 아이템 전체를 가져오는 경우 모두 서비스에서 리스트 전체를 가져와서 처리하는거라
api 를 두가지 만드는것보다 이런방법도 있구나 싶고 효율적인것 같아서 말씀드렸어요.
현업에서는 어떻게 이루어지는진 저는 잘 모르지만, 
HEAD로 Content-Length을 반환하는 것도 꽤나 많이 쓰는 방법인것 같더라고요ㅋㅋㅋㅋ

말씀하신대로 workers 자체가 full 데이터고 dto를 나타내니 
`workers?type=count, workers?type=dto` 요걸로 분리하는 것보다는 다른 방법이 나을 것 같구요,
`workers/counting` 이 방식은 쓰고싶지 않아서 다른 방법들을 찾아본거였는데
이게 제일 괜찮다고 생각하신다면 그렇게 가겠습니다!!

2022-07-16 06:21 UTC, dev-donghwan commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
@sypark9646 
음 차라리 HEAD로 Content-Length을 반환이게 더 나을거같긴하네요

2022-07-16 09:05 UTC, seung-00 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
> 민호님이 헤더에 뭐 넣으면 귀찮다고 말씀해주셨던 기억이 나긴 한다..ㅋㅋㅋㅋㅋㅋ
> `/api/v1/map/workers/counting` 이 방식이 프론트 입장에서는 더 편해서 추천을 하시는건가요?
> 아니면 불리언 값은 query 파라미터로

소연님 커스텀 헤더를 사용하신다는게 지금처럼 `respones: [...]` 은 유지하되 응답 헤더로 `count` 대신 Content-Length 에 값을 넣어줘서 프론트에서 사용하게 한다는 것 맞죠?

2022-07-16 09:17 UTC, seung-00 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
소연님 커스텀 헤더를 사용하신다는게 지금처럼 respones: [...] 은 유지하되 응답 헤더로 count 대신 Content-Length 에 값을 넣어줘서 프론트에서 사용하게 한다는 것 맞죠? 이유는 workers api 는 workers 만 응답에 있었으면 좋겠어서 그런거구요?

2022-07-16 15:06 UTC, sypark9646 commented
늦어서 죄송합니다!!

2022-07-16 15:14 UTC, sypark9646 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
앗 네네 맞습니당 일단은 엔드포인트 분리 해 뒀어요
엔드포인트 분리를 할거라면 workerList/workerSize 쿼리를 아예 다르게 하고싶었는데..ㅋㅋㅋ
jpql로 count 만 가져오도록하는게 생각보다 시간이 좀 걸릴것 같아서 추후에 추가해보겠습니다!!

2022-07-16 17:37 UTC, seung-00 commented on src/main/java/com/workat/api/map/dto/response/WorkerListResponse.java
> +	@JsonInclude(JsonInclude.Include.NON_NULL)
그렇군요. 비슷한 이유로 pagenation 을 구현할 때 page number, count 같은 것들을 헤더로 넣자는 논의가 회사에서 있긴 했었어요. 전 개인적으로 나쁘지 않았었고 관련된 레퍼런스도 있었던 것 같아서 다음에 FE 분들이랑 함께 얘기해봐도 좋을 것 같아요~

2022-07-16 17:42 UTC, seung-00 commented
> 늦어서 죄송합니다!! @seung-00 제가 제대로 고쳤는진 모르겠는데 토큰 만들때 oauthId, userId 로 만들고 있어서 일단 userId 로 만드는걸로 통일했습니다

앗 그러네요; 수정 감사합니다!!! ( _ _)

2022-07-17 07:10 UTC, dev-donghwan approved these changes

2022-07-17 07:40 UTC, merged