카페 리뷰 추가
work-at/backend pull request #53
Opened 2022-07-11 15:07 UTC by seung-00

#### AS-IS

#### TO-BE
* 카페 리뷰 추가 (Create, Read)
* CafeReviewType 정적 팩터리 함수 추가, DTO 수정

#### 리뷰시 중점 사항
* 특정 location 에 대한 카페 리뷰 (1:N) CREATE 관련
  * 한 번 CREATE 시 여러 type 가능. ex) POST ["와이파이가 좋아요", "주차 공간이 좋아요"]
  * 단 동일 user 가 동일한 locaiton 으로 여러번 요청 불가
* 카페 리뷰 조회는 count 를 기준으로 역순 정렬됨

#### 참조사항

2022-07-11 16:47 UTC, dev-donghwan requested changes

2022-07-11 16:47 UTC, dev-donghwan commented on src/main/java/com/workat/api/review/controller/ReviewController.java
> +	}
validation 체크가 되는건지 궁금합니다

2022-07-11 16:47 UTC, dev-donghwan commented on src/main/java/com/workat/api/review/dto/CafeReviewTypeDto.java
> +public class CafeReviewTypeDto {
이친구는 사용되는곳을 못찾겠는데 어디서 사용되는건가요?

2022-07-11 16:47 UTC, dev-donghwan commented on src/main/java/com/workat/api/review/service/ReviewService.java
> +																			counting()));
좋네요 활용

2022-07-11 16:47 UTC, dev-donghwan commented on src/main/java/com/workat/api/review/service/ReviewService.java
> +																 .collect(toList());
굿

2022-07-11 16:47 UTC, dev-donghwan commented on src/main/java/com/workat/api/review/controller/ReviewController.java
> +	}
그리고 뭔가 이게 굳이 단신으로 Get을 할때가 있을까요?
Location에 대한 상세정보를 가져가면 그 안에 같이 있어야하는 데이터가 아닐까 싶네요??

2022-07-11 16:47 UTC, dev-donghwan commented on src/main/java/com/workat/api/review/controller/ReviewController.java
> +	}
Post는 맞는거 같지만 Get의 활용이 단건조회(상세조회)라고 부르는 Response에 함께 가야할거같습니다.

2022-07-11 16:47 UTC, dev-donghwan commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +								Location location = Location.builder()
이거 혹시 convention이 뭐가 다른걸까요? 이건 리뷰와 상관없는 내용입니닼ㅋㅋ

2022-07-11 16:47 UTC, dev-donghwan commented on src/main/java/com/workat/api/review/controller/ReviewController.java
> +	}
그리고 추가적으로 그 Detail 또는 단건 정보를 줄 때, 이 유저가 이 Location은 리뷰를 했는지 boolean을 주는게 어떨까 싶네요!

2022-07-12 02:34 UTC, sypark9646 approved these changes
테스트를 잘 작성해주셔서 리뷰하기 편했습니당ㅋㅋㅋ👍👍👍

2022-07-12 02:34 UTC, sypark9646 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +@ExtendWith(MockitoExtension.class)
요건  `@Mock` 어노테이션을 사용하기 위한 extension인데
여기선 사용하지 않으니 삭제해도 될 것 같습니다!

2022-07-12 02:34 UTC, sypark9646 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +	void getCafeReviews() { // cafe 리뷰들 조회
Test 용도는 주석을 쓰셔도 좋지만 요런 방식도 있습니다~
```java
@DisplayName("cafe 리뷰들 조회")
```

2022-07-12 02:34 UTC, sypark9646 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +		assertTrue(allByLocation_idAndUser_id.size() == 3);
`Assertions.assertEquals(allByLocation_idAndUser_id.size(), 3)` 요렇게 쓸 수도 있겠네요~!

2022-07-12 02:34 UTC, sypark9646 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +	void addCafeReview_fail_duplicate_user() { // 중복된 유저 id 로 cafe 리뷰 추가한 경우 실패
컨테이너 뜬 상태에서는 테스트 실행하는 동안 데이터베이스가 유지되기 때문에 
(두 테스트가 동일한 location, user에 대해 insert 하고 있으니)
`cafe 리뷰 추가` 테스트 이후 `중복된 유저 id 로 cafe 리뷰 추가한 경우 실패` 테스트를 실행하도록 
`@Order` 을 주셔도 reviewService 두 번을 실행하지 않아도 테스트가 될 것 같아요!

저는 지금 작성하신 테스트도 좋으니 수정이 필요한 사항은 아닙니닷

2022-07-12 02:34 UTC, sypark9646 commented on src/main/java/com/workat/api/review/dto/response/ReviewTypeListResponse.java
>  	@ApiModelProperty(name = "response", notes = "리뷰 타입", example = "{\"response\":[{\"name\":\"PARKING\",\"content\":\"주차하기 편해요~\"},{\"name\":\"VIEW\",\"content\":\"뷰가 좋아요\"},{\"name\":\"NOT_CROWDED\",
```suggestion
	@ApiModelProperty(name = "response", notes = "리뷰 타입", example = "[{\"name\":\"PARKING\",\"content\":\"주차하기 편해요~\"},{\"name\":\"VIEW\",\"content\":\"뷰가 좋아요\"},{\"name\":\"NOT_CROWDED\",\"content\":\"한적해요~\"},{\"name\":\"NIGHT_VIEW\",\"content\":\"야경이 예뻐요~\"},{\"name\":\"SPACE\",\"content\":\"넓고 깨끗해요~\"},{\"name\":\"WIFI\",\"content\":\"와이파이가 빵빵해요!\"},{\"name\":\"POWER\",\"content\":\"콘센트 자리 많아요!\"},{\"name\":\"SEAT\",\"content\":\"좌석이 편해요\"},{\"name\":\"QUIET\",\"content\":\"조용한 공간이 있어요!\"},{\"name\":\"FOCUS\",\"content\":\"집중이 잘돼요\"}]")
```

요거 제가 잘못 작성한건데 요렇게 고쳐주실 수 있을까용??

2022-07-12 06:37 UTC, sypark9646 commented on src/main/java/com/workat/api/review/service/ReviewService.java
> +		final Optional<CafeReview> optionalCafeReview = cafeReviewRepository.findByLocation_IdAndUser_Id(
궁금한게 있는데 (Location_Id, User_Id) 를 가지는 리뷰가 많을 수도 있는데 요렇게 하면 가장 위에 있는거 하나 가져오는걸까요?!

2022-07-12 06:41 UTC, sypark9646 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +	void addCafeReview_fail_duplicate_user() { // 중복된 유저 id 로 cafe 리뷰 추가한 경우 실패
라고 생각했는데 `@DataJpaTest` 를 쓰셔서 테스트 하나가 끝나면 자동으로 insert 되었던게 비워져서 이렇게 하신거였군요ㅋㅋㅋ
몰랐습니다 죄송해요~~

2022-07-12 12:06 UTC, seung-00 commented on src/main/java/com/workat/api/review/controller/ReviewController.java
> +	}
> validation 체크가 되는건지 궁금합니다

user validation 말씀하시는걸까요? 제가 user 가 리뷰 했는지 여부 체크를 빼먹었네요. 이 부분이 추가되면 필요하겠군요

2022-07-12 12:16 UTC, seung-00 commented on src/main/java/com/workat/api/review/controller/ReviewController.java
> +	}
> 그리고 뭔가 이게 굳이 단신으로 Get을 할때가 있을까요? Location에 대한 상세정보를 가져가면 그 안에 같이 있어야하는 데이터가 아닐까 싶네요??

전 뭔가 로케이션 부분을 먼저 보여주는 것도 나쁘진 않을 것 같겠다 싶긴 했는데, 어차피 양이 많은 것도 아니니 합치는게 낫겠네요 ㅎㅎㅎ 반영하겠습니다

2022-07-12 12:16 UTC, seung-00 commented on src/main/java/com/workat/api/review/dto/CafeReviewTypeDto.java
> +public class CafeReviewTypeDto {
이 친구 빼는 걸 까먹었네요 ㅋㅋ 지우겠습니다

2022-07-12 12:19 UTC, seung-00 commented on src/main/java/com/workat/api/review/service/ReviewService.java
> +		final Optional<CafeReview> optionalCafeReview = cafeReviewRepository.findByLocation_IdAndUser_Id(
아 요기선 유저가 해당 로케이션에 리뷰를 남겼는지 여부를 체크하려고 했던거라서요. 맨 위에 있는거 하나만 가져오는 걸 의도한 게 맞습니다!

2022-07-12 12:19 UTC, seung-00 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +@ExtendWith(MockitoExtension.class)
앗 그렇군요 ㅎㅎㅎ 반영하겠습니다!

2022-07-12 12:27 UTC, seung-00 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +								Location location = Location.builder()
앗 ㅋㅋㅋ... 아마 아래 옵션을 제가 켜서 그런 것 같아요. 통일성이 없어지니까 앞으로는 꺼두도록 하겠습니다~
<img width="500" alt="image" src="https://user-images.githubusercontent.com/46865281/178488784-e8906238-2e42-4068-8fbc-12f7f8a57543.png">

2022-07-12 12:33 UTC, seung-00 commented on src/test/java/com/workat/api/review/service/ReviewServiceTest.java
> +	void addCafeReview_fail_duplicate_user() { // 중복된 유저 id 로 cafe 리뷰 추가한 경우 실패
오 네 @DataJpaTest에 @Transactional 가 있다고 하더라고요? ㅋㅋㅋ 어노테이션들 헷갈리네요 ㅎ

2022-07-16 17:32 UTC, seung-00 commented
@dev-donghwan 
리뷰해주신 수정사항 #58 에 반영했습니다~

2022-07-17 07:09 UTC, dev-donghwan approved these changes

2022-07-17 08:19 UTC, merged